service:
  port:
    name: HTTP
    l4_protocol: TCP
    port: 80
    targetPort: 80
  label: yoonsla1234-enxmngmvcw
  name: yoonsla1234-enxmngmvcw
  selector: yoonsla1234-enxmngmvcw
  type:
  - ClusterIP
  - NodePort
namespace: -@namespace@-
pvc:
  name: pvc-yoonsla1234-enxmngmvcw
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: yoonsla1234-enxmngmvcw
    type: react
  replicas: -@replicas@-
  update:
    type: RollingUpdate
  repo:
    url: -@imageRepoName@-
  image:
    name: yoonsla1234-enxmngmvcw
    tag: lastest
    secret: -@repoSecret@-
  container:
    name: yoonsla1234-enxmngmvcw
    port: 80
  volume:
    name: pvc-yoonsla1234-enxmngmvcw
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
  backing: 
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-yoonsla1234-enxmngmvcw
    minReplicas: -@minReplicas@-
    maxReplicas: -@maxReplicas@-
    cpu: -@cpuAutoScale@-
    memory: -@memAutoScale@-
